### ISSUE TITLE
implementation with angular

### ISSUE THREAD

**Issue by 0x14Rp** [IonicaBizau/node-gh-polyglot#18]
can I use this for an angular implementation? installing the dependency with npm and trying to use it tells me ERROR in C: /Users/gndx/node_modules/github-colors/lib/index.js
Module not found: Error: Can't resolve './colors' in 'C: \ Users \ gndx \ node_modules \ github-colors \ lib'
ERROR in C: /Users/gndx/node_modules/github-colors/lib/index.js
Module not found: Error: Can't resolve './extensions' in 'C: \ Users \ gndx \ node_modules \ github-colors \ lib' 🤔

**Comment by IonicaBizau** [comment]
I am not very good in Angular, but using it in Angular should be a problem... I'm not sure why you are getting that error, tho...
